=== muratcanakcay/Object-Oriented-Design-Lab-Tasks/Lab03/Xml.Library/tortoise_s.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://example.org/mca/tortoise"
    elementFormDefault="qualified"
    xmlns:tor="http://example.org/mca/tortoise"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  
  <!--startnumbers and track id must be UNIQUE!!!-->
  <!--event id must be UNIQUE!!! and must refer to a track id-->
  <!--participants must be UNIQUE in a single event!!! -->
  
  <!--Root-->
  <xs:element name="formulaT">
    <xs:complexType>
      <xs:sequence>
        <!--participants-->
        
        <xs:element name="participants" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tortoise" type="tor:tortoiseType" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="snail" type="tor:snailType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="uniqueNumber">
            <xs:selector xpath="tor:participants/tor:tortoise | tor:participants/tor:snail"/>
            <xs:field xpath="@startNumber"/>
          </xs:unique>
        </xs:element>
        
        <!--end of participants-->
        
        <xs:choice minOccurs="2" maxOccurs="unbounded">
          
          <xs:element name="track" type="tor:trackType">
            <xs:unique name="uniqueTrack">
              <xs:selector xpath="tor:track/tor:id"/>
              <xs:field xpath="."/>
            </xs:unique>
          </xs:element>

          <xs:element name="event" type="tor:eventType">
            <xs:unique name="uniqueParticipant">
              <xs:selector xpath="./tor:participant"/>
              <xs:field xpath="@id"/>
            </xs:unique>
          </xs:element>
          
        </xs:choice>
      </xs:sequence>
    </xs:complexType>


    <!--key ref-->
    <xs:key name="startNumberKey">
      <xs:selector xpath="tor:participants/tor:tortoise | tor:participants/tor:snail"/>
      <xs:field xpath="@startNumber"/>
    </xs:key>

    <xs:keyref name="idRef" refer="tor:startNumberKey">
      <xs:selector xpath="tor:event/tor:participant"/>
      <xs:field xpath="@id"/>
    </xs:keyref>

    <xs:key name="eventRef" >
      <xs:selector xpath="tor:track/tor:id"/>
      <xs:field xpath="."/>
    </xs:key>
    
    <xs:keyref name="trackKey" refer="tor:eventRef">
      <xs:selector xpath="tor:event/tor:track"/>
      <xs:field xpath="@id"/>
    </xs:keyref>

    
    
    <!--end of key ref-->
    
  </xs:element>
  <!--end of Root-->


  <!-- types -->
  <xs:complexType name="participantType">
    <xs:sequence>
      <xs:element name="nick" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="weight" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="startNumber" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="T[0-9]{2}"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="tortoiseType">
    <xs:complexContent>
      <xs:extension base="tor:participantType">
        <xs:sequence>
          <xs:element name="color" minOccurs="1" maxOccurs="1">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="green"/>
                <xs:enumeration value="dark green"/>
                <xs:enumeration value="light green"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="snailType">
    <xs:complexContent>
      <xs:extension base="tor:participantType">
        <xs:sequence>
          <xs:choice>
            <xs:element name="slow">
              <xs:complexType/>
            </xs:element>
            <xs:element name="fast">
              <xs:complexType/>
            </xs:element>
          </xs:choice>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="trackType">
    <xs:sequence>
      <xs:element name="id" type="xs:integer" minOccurs="1" maxOccurs="1"/>
      <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="length" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="eventType">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="date" type="xs:date" minOccurs="1" maxOccurs="1"/>
      <xs:element name="track" minOccurs="1" maxOccurs="1">
        <xs:complexType>
          <xs:attribute name="id" type="xs:integer" use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="participant" minOccurs="2" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!-- end of types -->
  
</xs:schema>

=== muratcanakcay/Object-Oriented-Design-Lab-Tasks/Lab03/Xml.Library/tortoise_s.xml
<?xml version="1.0" encoding="utf-8"?>
<formulaT xmlns="http://example.org/mca/tortoise"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://example.org/mca/tortoise tortoise_s.xsd">
  
  <participants>
    <tortoise startNumber="T23">
      <nick>Perry</nick>
      <weight>1.23</weight>
      <color>light green</color>
    </tortoise>
    <tortoise startNumber="T00">
      <nick>Pinky</nick>
      <weight>123.00</weight>
      <color>green</color>
    </tortoise>
    <snail startNumber="T93">
      <nick>Pete</nick>
      <weight>13</weight>
      <slow/>
    </snail>
    <snail startNumber="T01">
      <nick>Tricia</nick>
      <weight>22</weight>
      <fast/>
    </snail>
  </participants>
  <track>
    <id>13</id>
    <name>Yellowstone</name>
    <length>5.891</length>
  </track>
  <event>
    <name>Grand Prix of Slowness</name>
    <date>2021-04-02</date>
    <track id="13" />
    <participant id="T23"></participant>
    <participant id="T01"></participant>
  </event>
  <event>
    <name>Superfast Race</name>
    <date>2021-04-03</date>
    <track id="13" />
    <participant id="T00"/>
    <participant id="T23"></participant>
    <participant id="T93"></participant>
  </event>
  <track>
    <id>1</id>
    <name>SÅ‚omczyn</name>
    <length>7</length>
  </track>
</formulaT>
