=== muratcanakcay/Object-Oriented-Design-Lab-Tasks/Lab02/Xml.Data/library.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://example.org/mca/library"
    elementFormDefault="qualified"
    xmlns:lib="http://example.org/mca/library"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

  <!-- Root -->
  <xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        
        <!-- Library contents -->
        <xs:element name="books" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="book" type="lib:bookType" minOccurs="1" maxOccurs="unbounded">
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="journals" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="journal" type="lib:journalType" minOccurs="1" maxOccurs="unbounded">
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- End of library contents -->

        <!-- List of all authors -->
        <xs:element name="authors" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="author" type="lib:authorType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- End of list of all authors -->
        
      </xs:sequence>
    </xs:complexType>

    <!-- key-ref for authors -->
    <xs:key name="authorKey">
      <xs:selector xpath="lib:authors/lib:author"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="authorRef" refer="lib:authorKey">
      <xs:selector xpath="lib:book/lib:authors/lib:author"/>
      <xs:field xpath="@ref"/>
    </xs:keyref>
    <!-- end of key-ref for authors -->

    <!-- key-ref for editors -->
    <!--can I use the same key from authors and just refer to authorKey in editorRef?-->
    <xs:key name="editorKey">
      <xs:selector xpath="lib:authors/lib:author"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="editorRef" refer="lib:editorKey">
      <xs:selector xpath="lib:journal/lib:editors/lib:editor"/>
      <xs:field xpath="@ref"/>
    </xs:keyref>
    <!-- end of key-ref for editors -->
    
  </xs:element>
  <!-- end of Root -->


  <!--Types-->
  <xs:complexType name="documentType">  <!-- base type for book and journal -->
    <xs:sequence>
      <xs:element name="title" type="lib:titleType" minOccurs="1" maxOccurs="1"/>
      <xs:element name="year" type="lib:yearType" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="bookType">    <!-- extension from documentType -->
    <xs:complexContent>
      <xs:extension base="lib:documentType">
        <xs:sequence>
          <xs:element name="lang" type="lib:langType" minOccurs="1" maxOccurs="1"/>
          <xs:element name="authors" minOccurs="1" maxOccurs="1">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="author" minOccurs="1" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:attribute name="ref"/>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="journalType">    <!-- extension from documentType -->
    <xs:complexContent>
      <xs:extension base="lib:documentType">
        <xs:sequence>
          <xs:element name="issue" type="xs:integer" minOccurs="1" maxOccurs="1"/>
          <xs:element name="editors" minOccurs="1" maxOccurs="1">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="editor" minOccurs="1" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:attribute name="ref"/>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
      
  <xs:complexType name="authorType">
    <xs:sequence>
      <xs:element name="names" minOccurs="1" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="surname" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:simpleType name="titleType" >
    <xs:restriction base="xs:string">
      <xs:minLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="yearType" >
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1120"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="langType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EN"/>
      <xs:enumeration value="PL"/>
      <xs:enumeration value="TLH"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== muratcanakcay/Object-Oriented-Design-Lab-Tasks/Lab02/Xml.Data/bin/Debug/library.xml
<?xml version="1.0" encoding="utf-8"?>
<library xmlns="http://example.org/mca/library"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://example.org/mca/library library.xsd">
  <books>
    <book>
      <title>book1</title>
      <year>1945</year>
      <lang>EN</lang>
      <authors>
		    <author ref="1"/>
	    </authors>
    </book>
  
    <book>
      <title>book2</title>
      <year>1942</year>
      <lang>PL</lang>
	    <authors>
	   	  <author ref="1"/>
		    <author ref="2"/>
	    </authors>
    </book>
  
    <book>
      <title>book3</title>
      <year>1992</year>
      <lang>EN</lang>
      <authors>
		    <author ref="3"/>
		    <author ref="4"/>
	    </authors>
    </book>
  </books>

  <authors>
    <author id="1">
      <names>
        <name>author1name1</name>
      </names>
      <surname>author1surname</surname>
    </author>
    <author id="2">
      <names>
        <name>author2name1</name>
        <name>author2name2</name>
      </names>
      <surname>author2surname</surname>
    </author>
    <author id="3">
      <names>
        <name>author3name1</name>
        <name>author3name2</name>
      </names>
      <surname>author3surname</surname>
    </author>
    <author id="4">
      <names>
        <name>author4name1</name>
        <name>author4name2</name>
      </names>
      <surname>author4surname</surname>
    </author>
    <author id="5">  <!--This author is not used in the library-->
      <names>
        <name>author5name1</name>
        <name>author5name2</name>
      </names>
      <surname>author5surname</surname>
    </author>
  </authors>
  
</library>
